---
workflows:
  version: 2
  cron:
    #     triggers:
    #       - schedule:
    #           cron: "20 5 * * *"
    #           filters:
    #             branches:
    #               only:
    #                 - master
    jobs:
      - hello
jobs:
  hello:
    docker:
      - image: alpine:3.10.3
    steps:
      - run:
          name: hello
          command: echo hello
